site_name: blue-noise
repo_url: https://github.com/alexgQQ/blue-noise
site_url: https://alexgQQ.github.io/blue-noise
site_description: 
site_author: Alex Grand
edit_uri: edit/main/docs/
repo_name: alexgQQ/blue-noise
copyright: Maintained by <a href="https://alexgrand.dev">AG</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/alexgQQ/blue-noise
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/blue-noise

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true